In [1]:
import numpy 

In [ ]:
##Arrays

In [6]:
def arrays(arr):
    return(numpy.array(arr[::-1], float))
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [ ]:
##Shape and Reshape

In [8]:
print(numpy.array(input().split(),int).reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
##Transpose and Flatten

In [5]:
n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())


2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [ ]:
##Concatenate

In [3]:
n, m,p = map(int, input().split())
array1 = numpy.array([input().strip().split() for _ in range(n)], int)
array2 = numpy.array([input().strip().split() for _ in range(m)], int)
print(numpy.concatenate((array1, array2), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [ ]:
##Zeros and Ones

In [5]:
nums = tuple(map(int, input().split()))
print (numpy.zeros(nums, dtype = int))
print (numpy.ones(nums, dtype = int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [ ]:
##Eye and Identity

In [6]:
n,m = map(int, input().split(' '))
numpy.set_printoptions(sign=' ')
print(numpy.eye(n,m))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [ ]:
##Array Mathematics

In [3]:
n, m = map(int, input().split())
a = numpy.array([input().strip().split() for _ in range(n)], int)
b = numpy.array([input().strip().split() for _ in range(n)], int)
print (numpy.add(a, b) )
print (numpy.subtract(a, b))
print(numpy.multiply(a, b))
print (a//b)
print (a % b) 
print (a**b)       


1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [ ]:
##Floor, Ceil and Rint

In [4]:
my_array = numpy.array(input().split() , float)
numpy.set_printoptions(sign=' ')
print (numpy.floor(my_array))
print (numpy.ceil(my_array))
print (numpy.rint(my_array)) 


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [ ]:
##Sum and Prod

In [6]:
n, m = map(int, input().split())
arr = numpy.array([input().split() for _ in range(n)],int)
print(numpy.prod(numpy.sum(arr, axis=0), axis=0))

2 2
1 2
3 4
24


In [ ]:
##Min and Max

In [7]:
n, m = map(int, input().split())
arr = numpy.array([input().split() for _ in range(n)],int)
print(numpy.max(numpy.min(arr, axis=1)))

4 2
2 5
3 7
1 3
4 0
3


In [ ]:
##Mean, Var, and Std

In [2]:
n, m = map(int, input().split())
my_array = numpy.array([input().split() for _ in range(n)],int)
print (numpy.mean(my_array, axis = 1))
print (numpy.var(my_array, axis = 0))
print(round(numpy.std(my_array), 11))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.11803398875


In [ ]:
##Dot and Cross

In [3]:
n= int(input())
a = numpy.array([input().strip().split() for _ in range(n)], int)
b = numpy.array([input().strip().split() for _ in range(n)], int)
print (numpy.dot(a,b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [ ]:
##Inner and Outer

In [4]:
a = numpy.array(input().strip().split() , int)
b = numpy.array(input().strip().split(), int)
print (numpy.inner(a,b))
print (numpy.outer(a,b))

0 1
2 3
3
[[0 0]
 [2 3]]


In [ ]:
##Polynomials

In [5]:
a = numpy.array(input().strip().split() , float)
x=int(input())
print (numpy.polyval(a,x))

1.1 2 3
0
3.0


In [ ]:
##Linear Algebra

In [6]:
import numpy
n= int(input())
a = numpy.array([input().strip().split() for _ in range(n)], float)
print (round(numpy.linalg.det(a) ,2))

2
1.1 1.1
1.1 1.1
0.0


In [ ]:
##